- REQUIRE
- src/navigation.jl
* depends on Compat for older Julia versions
This PR should only be merged after https://github.com/JuliaLang/Compat.jl/pull/103 is merged and a new Compat is tagged.
@timholy, these changes should be correct, but I don't have a good way to test them.
> RFC: Adapt Timer code to v0.4 changes (don't merge yet)

- .travis.yml
- src/annotations.jl
- src/display.jl
- test/REQUIRE
- test/tile.jl
This is a minimal fix to get the tests working again. Pretty amazing, really, that this is all it took.
The deprecation warnings are outrageous, but that will be fixed eventually by the Gtk rewrite.
> Provide scoping for Graphics.save

- src/annotations.jl
- src/display.jl
This avoids most deprecation warnings when `using ImageView` from Julia 0.4. 
Note 1: Latest tagged version of IniFile.jl gives a lot of warnings as well, so it's worth to checkout its master.
Note 2: Even with these changes, 3 warnings persist: 
```
WARNING: requiring "Dates" in module "Winston" did not define a corresponding module.
WARNING: module Winston should explicitly import * from Base
WARNING: could not import Images.scaleinfo into ImageView
```
I suppose to fix the last one it's safe to just delete `import Images.scaleinfo` from display.jl, while first two require additional pull request to Winston package.
> Changes for julia v0.4

- REQUIRE
instead of assuming it will be present from other dependencies
ImageView could also use a Travis badge in the readme.
> add Cairo explicitly to REQUIRE

- .travis.yml
- REQUIRE
No new tags are accepted for julia 0.3, so let's make 0.4 the minimum version.
> Bump minimum julia to 0.4

- test/REQUIRE
since they're imported directly by the tests - they should
be present as transitive dependencies of GtkReactive and Images,
but hypothetically that might not always be the case
> Add Reactive and ImageCore to test/REQUIRE

- .travis.yml
- src/ImageView.jl
- src/slicing.jl
- test/test4d.jl
The documentation suggested that one could pass in a `CLim` object, but it didn't work unless it was really a `Signal{CLim}`, which is too finicky for users. This allows the `CLim`.
> Fix handling of clim

- src/ImageView.jl
- src/contrast_gui.jl
- test/contrast.jl
This is a tiny change on top of #145, which will hopefully get it passing tests. CC @Cody-G
> Per-channel contrast

- .travis.yml
- REQUIRE
I know this will be requested before tagging another release that doesn't support Julia 0.7, so let's just do it ahead of time.
> Restrict current release to Julia 0.6

- src/ImageView.jl
Currently, unless the user captures the output Dict as a variable, there is some risk that the signals will get garbage-collected. This adds a few missing `gc_preserve`s to ensure that they persist as long as the window does.
Due to a bug in GtkReactive, this will only fix the problem with GtkReactive 0.5.3 or higher (see https://github.com/JuliaGizmos/GtkReactive.jl/pull/83), but there seems no harm in it even with lower versions of GtkReactive.
> Preserve signals until window is destroyed

- src/ImageView.jl
- test/contrast.jl
We make `enabled` an unused dependency of the histogram-calculating code, thus ensuring it updates.
> Update histogram whenever `enabled` changes state (fixes #168)

- src/ImageView.jl
- src/precompile.jl
- test/runtests.jl
These collectively shave almost 10s off inference time when running the  tests.
> Add precompiles and nospecialize annotations

- .github/workflows/CompatHelper.yml
The CompatHelper script gives this interesting message:
```
[ Info: This doesn't look like a raw SSH private key. I will assume that it is a Base64-encoded SSH private key. I will now try to Base64-decode it.
[ Info: This was a Base64-encoded SSH private key. I Base64-decoded it, and now I have the raw SSH private key.
```
but then various "permission denied" errors follow.
This switches to the TAGBOT key like Images.jl.
> Switch to TAGBOT key for CompatHelper

- .github/workflows/CI.yml
- Project.toml
Given that Julia 1.0 can't build Gtk anymore on any platform, it's time for a breaking release. We might as well jump to the next LTS.
> Make 1.6LTS the earliest supported version

- src/ImageView.jl
- test/newtests.jl
xref https://github.com/JuliaAstro/AstroImages.jl/issues/10 and
https://discourse.julialang.org/t/plotting-image-data-in-julia-is-much-slower-than-matlab/79660
> Support very large images with `restrict`

- src/ImageView.jl
- test/newtests.jl
Discovering errors during rendering is not ideal, because it's quite
hard to trace back to the original cause. This puts in a simple
check before rendering the suitably-scaled image.
> Make it easier to identify mapping errors

- src/ImageView.jl
- test/core.jl
- test/runtests.jl
`scaleminmax` is owned by ImageCore and the colors it operates
on are owned by ColorTypes. In contrast to both Colors and
ColorVectorspace, for which piracy is their raison d'etre,
this is not really a sanctioned case of piracy.
We could add these methods to ImageCore, but I think they'd be a
little dicey, so best to make them internal.
> Stop pirating `scaleminmax`

- Project.toml
- src/ImageView.jl
On my machine, on `master` with Julia 1.6:
```
julia> @time using ImageCore, ImageView
3.133214 seconds (7.36 M allocations: 474.322 MiB, 9.91% gc time, 43.39% compilation time)
julia> @time @eval img = rand(RGB{N0f8}, 100, 120);
0.156444 seconds (825.12 k allocations: 49.383 MiB, 11.35% gc time, 99.81% compilation time)
julia> @time @eval h = imshow(img);
2.514401 seconds (8.79 M allocations: 520.388 MiB, 4.35% gc time, 4.57% compilation time)
```
With Julia nightly, on the master branch of ImageView it's somewhat better:
```
julia> @time using ImageCore, ImageView
2.439186 seconds (6.09 M allocations: 382.197 MiB, 7.44% gc time, 14.67% compilation time)
julia> @time @eval img = rand(RGB{N0f8}, 100, 120);
0.121767 seconds (260.59 k allocations: 17.305 MiB, 12.40% gc time, 168.10% …
```
> Switch to SnoopPrecompile for precompilation

- src/ImageView.jl
- src/contrast_gui.jl
This caused a block in precompilation on 1.10 due to waiting for IO operations to complete., but it's also a nice usability enhancement.
> `closeall` also handles contrast windows

- Project.toml
`Gtk4.add_action_shortcut` first appeared in Gtk4 v0.6.2 and is required
for successful precompilation. This ensures that the resolver doesn't
get into a state where it installs an earlier Gtk4 version.
> [compat]: require Gtk4 v0.6.2

- src/contrast_gui.jl
Convert new contrast limit values to the right type and only update if the new values are different from the old values.
Prevents a crash when the contrast bars cross.
Fixes #308
It would be ideal to add a test too, but I don't have time this morning.
> Prevent an infinite loop in the contrast GUI

- .github/workflows/CI.yml
- Project.toml
- README.md
- src/ImageView.jl
Label shows the current view (only when zoomed in). This is selectable, allowing users to cut and paste into an editor (or the REPL).
Also includes a microoptimization in the hover label setter and a minor fix to the README.
Finally, require Julia 1.10 and bump version.
> Label in the bottom right corner showing the current view

- Project.toml
- README.md
- ext/ImageViewFileIOExt.jl
- src/ImageView.jl
When FileIO is present, `imshow()` will open an image using a dialog.
Fixes https://github.com/JuliaImages/ImageView.jl/issues/291.
> FileIO extension for imshow()
